on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: [20]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5.1.0

      - uses: actions/setup-node@v5.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Electron
        uses: actions/cache@v5.1.0
        with:
          path: |
            ~\AppData\Local\electron\Cache
            ~/Library/Caches/electron
            ~/.cache/electron
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-

      - run: npm ci
